create table if not exists public.users (
  id uuid primary key references auth.users(id) on delete cascade,
  name text not null,
  email text not null unique,
  created_date timestamptz not null default now()
);

create table if not exists public.leads (
  id bigint generated by default as identity primary key,
  name text not null,
  company text not null,
  email text not null,
  phone text,
  source text not null,
  salesperson text,
  status text not null default 'New'
    check (status in ('New', 'Contacted', 'Qualified', 'Proposal Sent', 'Won', 'Lost')),
  deal_value numeric(12, 2) not null default 0,
  created_date timestamptz not null default now(),
  updated_date timestamptz not null default now()
);

create table if not exists public.notes (
  id bigint generated by default as identity primary key,
  lead_id bigint not null references public.leads(id) on delete cascade,
  content text not null,
  created_by text not null,
  created_date timestamptz not null default now()
);

create index if not exists leads_status_idx on public.leads(status);
create index if not exists leads_source_idx on public.leads(source);
create index if not exists notes_lead_id_idx on public.notes(lead_id);
create index if not exists users_email_idx on public.users(email);

create or replace function public.set_updated_date()
returns trigger as $$
begin
  new.updated_date = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists set_leads_updated_date on public.leads;
create trigger set_leads_updated_date
before update on public.leads
for each row
execute function public.set_updated_date();

alter table public.users enable row level security;
alter table public.leads enable row level security;
alter table public.notes enable row level security;

drop policy if exists "Authenticated users can read users" on public.users;
create policy "Authenticated users can read users"
on public.users
for select
to authenticated
using (true);

drop policy if exists "Users can insert their own profile" on public.users;
create policy "Users can insert their own profile"
on public.users
for insert
to authenticated
with check (auth.uid() = id);

drop policy if exists "Users can update their own profile" on public.users;
create policy "Users can update their own profile"
on public.users
for update
to authenticated
using (auth.uid() = id)
with check (auth.uid() = id);

drop policy if exists "Authenticated users can manage leads" on public.leads;
create policy "Authenticated users can manage leads"
on public.leads
for all
to authenticated
using (true)
with check (true);

drop policy if exists "Authenticated users can manage notes" on public.notes;
create policy "Authenticated users can manage notes"
on public.notes
for all
to authenticated
using (true)
with check (true);
